// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: public_member_api_docs, prefer_single_quotes, avoid_escaping_inner_quotes, prefer_const_constructors, sort_constructors_first, always_specify_types, non_constant_identifier_names

// Dart imports:
import 'dart:async';

// Flutter imports:
import 'package:flutter/widgets.dart';

/// A class generated by flappy_translator package containing localized strings
class Translations {
  static String get about => _getText("about");

  static String get about_text => _getText("about_text");

  static String get add => _getText("add");

  static String get add_group => _getText("add_group");

  static String get add_subject => _getText("add_subject");

  static String get add_subjects => _getText("add_subjects");

  static String get add_test => _getText("add_test");

  static String get app_name => _getText("app_name");

  static String get app_version => _getText("app_version");

  static String get appearance => _getText("appearance");

  static String get average => _getText("average");

  static String get az => _getText("az");

  static String get basic => _getText("basic");

  static String get bonus => _getText("bonus");

  static String get cancel => _getText("cancel");

  static String get change_class => _getText("change_class");

  static String get change_class_summary => _getText("change_class_summary");

  static String get class_string => _getText("class_string");

  static String get classic => _getText("classic");

  static String get coefficient => _getText("coefficient");

  static String get coefficient_dots => _getText("coefficient_dots");

  static String get coefficients => _getText("coefficients");

  static String get coming_soon => _getText("coming_soon");

  static String get confirm => _getText("confirm");

  static String get confirm_delete => _getText("confirm_delete");

  static String get contact => _getText("contact");

  static String get custom => _getText("custom");

  static String get custom_rating_system => _getText("custom_rating_system");

  static String get default_string => _getText("default_string");

  static String get delete => _getText("delete");

  static String get down => _getText("down");

  static String get edit => _getText("edit");

  static String get edit_group => _getText("edit_group");

  static String get edit_subject => _getText("edit_subject");

  static String get edit_subjects => _getText("edit_subjects");

  static String get edit_subjects_summary => _getText("edit_subjects_summary");

  static String get edit_test => _getText("edit_test");

  static String get email => _getText("email");

  static String get english => _getText("english");

  static String get enter_unique => _getText("enter_unique");

  static String get exam => _getText("exam");

  static String get exams => _getText("exams");

  static String get export_details => _getText("export_details");

  static String get export_string => _getText("export_string");

  static String get french => _getText("french");

  static String get general => _getText("general");

  static String get german => _getText("german");

  static String get github => _getText("github");

  static String get github_summary => _getText("github_summary");

  static String get grade => _getText("grade");

  static String get grades => _getText("grades");

  static String get group => _getText("group");

  static String get half_down => _getText("half_down");

  static String get half_up => _getText("half_up");

  static String get import_details => _getText("import_details");

  static String get import_error => _getText("import_error");

  static String get import_string => _getText("import_string");

  static String get import_success => _getText("import_success");

  static String get invalid => _getText("invalid");

  static String get language => _getText("language");

  static String get licenses => _getText("licenses");

  static String get lux_system => _getText("lux_system");

  static String get luxemburgish => _getText("luxemburgish");

  static String get maximum => _getText("maximum");

  static String get more_options => _getText("more_options");

  static String get name => _getText("name");

  static String get next => _getText("next");

  static String get no => _getText("no");

  static String get not_set => _getText("not_set");

  static String get note => _getText("note");

  static String get note_text => _getText("note_text");

  static String get ok => _getText("ok");

  static String get open => _getText("open");

  static String get other_system => _getText("other_system");

  static String get previous => _getText("previous");

  static String get rating_system => _getText("rating_system");

  static String get reset => _getText("reset");

  static String get reset_summary => _getText("reset_summary");

  static String get round_to => _getText("round_to");

  static String get rounding_mode => _getText("rounding_mode");

  static String get save => _getText("save");

  static String get school_system => _getText("school_system");

  static String get section => _getText("section");

  static String get section_classic_a => _getText("section_classic_a");

  static String get section_classic_b => _getText("section_classic_b");

  static String get section_classic_c => _getText("section_classic_c");

  static String get section_classic_d => _getText("section_classic_d");

  static String get section_classic_e => _getText("section_classic_e");

  static String get section_classic_f => _getText("section_classic_f");

  static String get section_classic_g => _getText("section_classic_g");

  static String get section_classic_i => _getText("section_classic_i");

  static String get section_general_a3d => _getText("section_general_a3d");

  static String get section_general_acv => _getText("section_general_acv");

  static String get section_general_cc => _getText("section_general_cc");

  static String get section_general_cf => _getText("section_general_cf");

  static String get section_general_cg => _getText("section_general_cg");

  static String get section_general_cm => _getText("section_general_cm");

  static String get section_general_ed => _getText("section_general_ed");

  static String get section_general_gh => _getText("section_general_gh");

  static String get section_general_ig => _getText("section_general_ig");

  static String get section_general_in => _getText("section_general_in");

  static String get section_general_mm => _getText("section_general_mm");

  static String get section_general_ps => _getText("section_general_ps");

  static String get section_general_se => _getText("section_general_se");

  static String get section_general_sh => _getText("section_general_sh");

  static String get section_general_si => _getText("section_general_si");

  static String get section_general_sn => _getText("section_general_sn");

  static String get section_general_so => _getText("section_general_so");

  static String get select_term => _getText("select_term");

  static String get semester => _getText("semester");

  static String get semesters => _getText("semesters");

  static String get settings => _getText("settings");

  static String get setup => _getText("setup");

  static String get sort_by => _getText("sort_by");

  static String get storage_error => _getText("storage_error");

  static String get subject => _getText("subject");

  static String get system => _getText("system");

  static String get system_language => _getText("system_language");

  static String get term => _getText("term");

  static String get test => _getText("test");

  static String get theme => _getText("theme");

  static String get theme_dark => _getText("theme_dark");

  static String get theme_light => _getText("theme_light");

  static String get theme_system => _getText("theme_system");

  static String get to_100th => _getText("to_100th");

  static String get to_10th => _getText("to_10th");

  static String get to_integer => _getText("to_integer");

  static String get trimester => _getText("trimester");

  static String get trimesters => _getText("trimesters");

  static String get up => _getText("up");

  static String get variant => _getText("variant");

  static String get variant_classic_l => _getText("variant_classic_l");

  static String get variant_classic_zh => _getText("variant_classic_zh");

  static String get variant_general_a => _getText("variant_general_a");

  static String get variant_general_ad => _getText("variant_general_ad");

  static String get variant_general_adf => _getText("variant_general_adf");

  static String get variant_general_f => _getText("variant_general_f");

  static String get variant_general_fr => _getText("variant_general_fr");

  static String get variant_general_ia => _getText("variant_general_ia");

  static String get variant_general_if => _getText("variant_general_if");

  static String get variant_general_p => _getText("variant_general_p");

  static String get variant_general_pf => _getText("variant_general_pf");

  static String get year => _getText("year");

  static String get year_overview => _getText("year_overview");

  static String get yearly_average => _getText("yearly_average");

  static String get yes => _getText("yes");

  static late Map<String, String> _localizedValues;

  static const _enValues = {
    "about": "About",
    "about_text": "NightDream Games\nDeveloper - Damien Pirotte\nVisual identity - Ellia Walrave\nTesting - Louis Colbus",
    "add": "Add",
    "add_group": "Add group",
    "add_subject": "Add subject",
    "add_subjects": "Add subjects",
    "add_test": "Add test",
    "app_name": "Graded",
    "app_version": "App version",
    "appearance": "Appearance",
    "average": "Average",
    "az": "A-Z",
    "basic": "Basic",
    "bonus": "Bonus:",
    "cancel": "Cancel",
    "change_class": "Change class",
    "change_class_summary": "Click to change your current class. This will delete all your saved grades.",
    "class_string": "Class",
    "classic": "Classic",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "coming_soon": "Coming soon",
    "confirm": "Confirm",
    "confirm_delete": "Are you sure you want to delete all your saved grades?",
    "contact": "Contact us",
    "custom": "Custom",
    "custom_rating_system": "Custom rating system",
    "default_string": "Default",
    "delete": "Delete",
    "down": "Down",
    "edit": "Edit",
    "edit_group": "Edit group",
    "edit_subject": "Edit subject",
    "edit_subjects": "Edit subjects",
    "edit_subjects_summary": "Click to edit your subjects",
    "edit_test": "Edit test",
    "email": "contact@nightdreamgames.com",
    "english": "English",
    "enter_unique": "Enter a unique name",
    "exam": "Exam",
    "exams": "Exams",
    "export_details": "Export the current configuration and saved data",
    "export_string": "Export",
    "french": "Français",
    "general": "General",
    "german": "Deutsch",
    "github": "GitHub repository",
    "github_summary": "https://github.com/NightDreamGames/Graded",
    "grade": "Grade",
    "grades": "Grades",
    "group": "Group",
    "half_down": "Half down",
    "half_up": "Half up",
    "import_details": "Import a previously exported backup file",
    "import_error": "There was an error importing your backup.",
    "import_string": "Import",
    "import_success": "Backup imported successfully.",
    "invalid": "Invalid",
    "language": "Language",
    "licenses": "Licenses",
    "lux_system": "Luxemburgish school system",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "more_options": "More options",
    "name": "Name",
    "next": "Next",
    "no": "No",
    "not_set": "Not set",
    "note": "Note:",
    "note_text": "You can always edit your subjects and other options in the settings later",
    "ok": "OK",
    "open": "Open",
    "other_system": "Other school system",
    "previous": "Previous",
    "rating_system": "Rating system",
    "reset": "Reset Grades",
    "reset_summary": "Delete all saved grades and reset app",
    "round_to": "Round to",
    "rounding_mode": "Rounding mode",
    "save": "Save",
    "school_system": "School system",
    "section": "Section",
    "section_classic_a": "A - Languages",
    "section_classic_b": "B - Mathematics",
    "section_classic_c": "C - Natural sciences",
    "section_classic_d": "D - Economics",
    "section_classic_e": "E - Art",
    "section_classic_f": "F - Music",
    "section_classic_g": "G - Human and social sciences",
    "section_classic_i": "I - Informatics & Communication",
    "section_general_a3d": "A3D - Architecture, design and sustainable development",
    "section_general_acv": "ACV - Arts and visual communication",
    "section_general_cc": "CC - Communication and organization",
    "section_general_cf": "CF - Finance",
    "section_general_cg": "CG - Management",
    "section_general_cm": "CM - Administrative and commercial",
    "section_general_ed": "ED - Educator training",
    "section_general_gh": "GH - Hospitality management",
    "section_general_ig": "IG - Engineering",
    "section_general_in": "IN - Informatics",
    "section_general_mm": "MM - Marketing, media and communication",
    "section_general_ps": "PS - Health and social professions",
    "section_general_se": "SE - Environmental sciences",
    "section_general_sh": "SH - Health sciences",
    "section_general_si": "SI - Nurse training",
    "section_general_sn": "SN - Natural sciences",
    "section_general_so": "SO - Social sciences",
    "select_term": "Select term",
    "semester": "Semester",
    "semesters": "Semesters",
    "settings": "Settings",
    "setup": "Setup",
    "sort_by": "Sort by",
    "storage_error": "There was an error loading your saved data, so it has been deleted.",
    "subject": "Subject",
    "system": "System",
    "system_language": "System language",
    "term": "Term",
    "test": "Test",
    "theme": "Theme",
    "theme_dark": "Dark",
    "theme_light": "Light",
    "theme_system": "System (recommended)",
    "to_100th": "To 100-th",
    "to_10th": "To 10-th",
    "to_integer": "To integer",
    "trimester": "Trimester",
    "trimesters": "Trimesters",
    "up": "Up",
    "variant": "Variant",
    "variant_classic_l": "L - Latin",
    "variant_classic_zh": "ZH - Chinese",
    "variant_general_a": "A - Continuation of german",
    "variant_general_ad": "AD - Adaptation class",
    "variant_general_adf": "ADF - French adaptation class",
    "variant_general_f": "F - Beginning of german",
    "variant_general_fr": "FR - Francophone regime",
    "variant_general_ia": "IA - Learning german",
    "variant_general_if": "IF - Learning french",
    "variant_general_p": "P - Preparation route",
    "variant_general_pf": "PF - French preparation way",
    "year": "Year",
    "year_overview": "Year overview",
    "yearly_average": "Yearly average",
    "yes": "Yes",
  };

  static const _frValues = {
    "about": "À propos",
    "about_text": "NightDream Games\nDéveloppeur - Damien Pirotte\nIdentité visuelle - Ellia Walrave\nTesting - Louis Colbus",
    "add": "Ajouter",
    "add_group": "Ajouter un groupe",
    "add_subject": "Ajouter une matière",
    "add_subjects": "Ajouter des matières",
    "add_test": "Ajouter un devoir",
    "app_name": "Graded",
    "app_version": "Version de l'application",
    "appearance": "Apparence",
    "average": "Moyenne",
    "az": "A-Z",
    "basic": "Basique",
    "bonus": "Bonus:",
    "cancel": "Annuler",
    "change_class": "Changer la classe",
    "change_class_summary": "Cliquez pour changer votre classe actuelle. Cela supprimera toutes vos notes sauvegardées.",
    "class_string": "Classe",
    "classic": "Classique",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "coming_soon": "Bientôt disponible",
    "confirm": "Confirmation",
    "confirm_delete": "Êtes-vous sûr de vouloir supprimer toutes vos notes enregistrées ?",
    "contact": "Contact",
    "custom": "Personnalisé",
    "custom_rating_system": "Système de notation personnalisé",
    "default_string": "Par défaut",
    "delete": "Supprimer",
    "down": "Vers le bas",
    "edit": "Modifier",
    "edit_group": "Modifier un groupe",
    "edit_subject": "Modifier une matière",
    "edit_subjects": "Modifier matières",
    "edit_subjects_summary": "Cliquez pour modifier vos matières.",
    "edit_test": "Modifier un devoir",
    "email": "contact@nightdreamgames.com",
    "english": "English",
    "enter_unique": "Entrez un nom unique",
    "exam": "Examen",
    "exams": "Examens",
    "export_details": "Exporter la configuration actuelle et les données sauvegardées",
    "export_string": "Exporter",
    "french": "Français",
    "general": "Général",
    "german": "Deutsch",
    "github": "Repository GitHub",
    "github_summary": "https://github.com/NightDreamGames/Graded",
    "grade": "Note",
    "grades": "Notes",
    "group": "Groupe",
    "half_down": "A moitié vers le bas",
    "half_up": "A moitié vers le haut",
    "import_details": "Importer un fichier de sauvegarde précédemment exporté",
    "import_error": "Une erreur s'est produite lors de l'import de votre sauvegarde.",
    "import_string": "Importer",
    "import_success": "Sauvegarde importée avec succès.",
    "invalid": "Invalide",
    "language": "Langue",
    "licenses": "Licenses",
    "lux_system": "Système scolaire luxembourgeois",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "more_options": "Plus d'options",
    "name": "Nom",
    "next": "Suivant",
    "no": "Non",
    "not_set": "Non défini",
    "note": "Note:",
    "note_text": "Vous pouvez toujours modifier vos matières et les autres options dans les paramètres plus tard",
    "ok": "OK",
    "open": "Ouvrir",
    "other_system": "Autre système scolaire",
    "previous": "Précédent",
    "rating_system": "Système de notation",
    "reset": "Réinitialiser les notes",
    "reset_summary": "Supprimer toutes les notes enregistrées et réinitialiser l'application",
    "round_to": "Arrondir à",
    "rounding_mode": "Mode arrondissage",
    "save": "Sauvegarder",
    "school_system": "Système scolaire",
    "section": "Section",
    "section_classic_a": "A - Langues",
    "section_classic_b": "B - Mathematiques",
    "section_classic_c": "C - Sciences naturelles",
    "section_classic_d": "D - Economie",
    "section_classic_e": "E - Artistique",
    "section_classic_f": "F - Musique",
    "section_classic_g": "G - Sciences humaines et sociales",
    "section_classic_i": "I - Informatique & Communication",
    "section_general_a3d": "A3D - Architecture, design et développement durable",
    "section_general_acv": "ACV - Arts et communication visuelle",
    "section_general_cc": "CC - Communication et organisation",
    "section_general_cf": "CF - Finance",
    "section_general_cg": "CG - Gestion",
    "section_general_cm": "CM - Administratif et commercial",
    "section_general_ed": "ED - Formation de l'éducateur",
    "section_general_gh": "GH - Gestion de l'hospitalité",
    "section_general_ig": "IG - Ingénierie",
    "section_general_in": "IN - Informatique",
    "section_general_mm": "MM - Marketing, médias et communication",
    "section_general_ps": "PS - Professions de santé et professions sociales",
    "section_general_se": "SE - Sciences environnementales",
    "section_general_sh": "SH - Sciences de la santé",
    "section_general_si": "SI - Formation de l'infirmier",
    "section_general_sn": "SN - Sciences naturelles",
    "section_general_so": "SO - Sciences sociales",
    "select_term": "Sélectionner période",
    "semester": "Semestre",
    "semesters": "Semestres",
    "settings": "Options",
    "setup": "Configuration",
    "sort_by": "Trier par",
    "storage_error": "Une erreur s'est produite lors du chargement de vos données sauvegardées, elles ont donc été supprimées.",
    "subject": "Matière",
    "system": "Système",
    "system_language": "Langue du système",
    "term": "Période",
    "test": "Devoir",
    "theme": "Thème",
    "theme_dark": "Sombre",
    "theme_light": "Clair",
    "theme_system": "Système (recommandé)",
    "to_100th": "Au 100ème",
    "to_10th": "Au 10ème",
    "to_integer": "A l'entier",
    "trimester": "Trimestre",
    "trimesters": "Trimestres",
    "up": "Vers le haut",
    "variant": "Variante",
    "variant_classic_l": "L - Latin",
    "variant_classic_zh": "ZH - Chinois",
    "variant_general_a": "A - Continuation de l'allemand",
    "variant_general_ad": "AD - Classe d'adaptation",
    "variant_general_adf": "ADF - Classe d'adaptation française",
    "variant_general_f": "F - Début de l'allemand",
    "variant_general_fr": "FR - Régime francophone",
    "variant_general_ia": "IA - Apprentissage de l'allemand",
    "variant_general_if": "IF - Apprentissage du français",
    "variant_general_p": "P - Voie de préparation",
    "variant_general_pf": "PF - Voie de préparation française",
    "year": "Année",
    "year_overview": "Aperçu de l'année",
    "yearly_average": "Moyenne annuelle",
    "yes": "Oui",
  };

  static const _deValues = {
    "about": "Informationen",
    "about_text": "NightDream Games\nEntwickler - Damien Pirotte\nVisuelle Identität - Ellia Walrave\nTesting - Louis Colbus",
    "add": "Hinzufügen",
    "add_group": "Gruppe hinzufügen",
    "add_subject": "Fach hinzufügen",
    "add_subjects": "Fächer hinzufügen",
    "add_test": "Prüfung hinzufügen",
    "app_name": "Graded",
    "app_version": "App-Version",
    "appearance": "Aussehen",
    "average": "Durchschnitt",
    "az": "A-Z",
    "basic": "Basic",
    "bonus": "Bonus:",
    "cancel": "Abbrechen",
    "change_class": "Klasse ändern",
    "change_class_summary": "Klicken Sie um Ihre aktuelle Klasse zu ändern. Alle gespeicherten Noten werden dabei gelöscht.",
    "class_string": "Klasse",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffiziente",
    "coming_soon": "Demnächst verfügbar",
    "confirm": "Bestätigung",
    "confirm_delete": "Sind Sie sicher, dass Sie alle Ihre gespeicherten Noten löschen wollen?",
    "contact": "Kontakt",
    "custom": "Personalisiert",
    "custom_rating_system": "Personalisiertes Bewertungssystem",
    "default_string": "Default",
    "delete": "Löschen",
    "down": "Nach unten",
    "edit": "Bearbeiten",
    "edit_group": "Gruppe bearbeiten",
    "edit_subject": "Fach bearbeiten",
    "edit_subjects": "Fächer bearbeiten",
    "edit_subjects_summary": "Klicken Sie um Ihre Fächer zu bearbeiten",
    "edit_test": "Prüfing bearbeiten",
    "email": "contact@nightdreamgames.com",
    "english": "English",
    "enter_unique": "Geben Sie einen eindeutigen Namen ein",
    "exam": "Examen",
    "exams": "Examen",
    "export_details": "Exportieren der aktuellen Konfiguration und der gespeicherten Daten",
    "export_string": "Exportieren",
    "french": "Français",
    "general": "General",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Graded",
    "grade": "Note",
    "grades": "Noten",
    "group": "Gruppe",
    "half_down": "Halb nach unten",
    "half_up": "Halb nach oben",
    "import_details": "Importieren einer zuvor exportierten Backup-Datei",
    "import_error": "Es ist ein Fehler beim Importieren Ihrer Backup aufgetreten.",
    "import_string": "Importieren",
    "import_success": "Backup erfolgreich importiert.",
    "invalid": "Ungültig",
    "language": "Sprache",
    "licenses": "Lizenzen",
    "lux_system": "Luxemburgisches Schulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "more_options": "Mehr Optionen",
    "name": "Name",
    "next": "Weiter",
    "no": "Nein",
    "not_set": "Nicht definiert",
    "note": "Anmerkung:",
    "note_text": "Sie können Ihre Fächer und andere Optionen später immer noch in den Einstellungen bearbeiten",
    "ok": "OK",
    "open": "Öffnen",
    "other_system": "Anderes Schulsystem",
    "previous": "Zurück",
    "rating_system": "Bewertungssystem",
    "reset": "Noten zurücksetzen",
    "reset_summary": "Alle gespeicherten Noten löschen und App zurücksetzen",
    "round_to": "Runden bis",
    "rounding_mode": "Abrundungsmodus",
    "save": "Speichern",
    "school_system": "Schulsystem",
    "section": "Sektion",
    "section_classic_a": "A - Sprachen",
    "section_classic_b": "B - Mathematik",
    "section_classic_c": "C - Naturwissenschaften",
    "section_classic_d": "D - Wirtschaft",
    "section_classic_e": "E - Kunst",
    "section_classic_f": "F - Musik",
    "section_classic_g": "G -Menschliche und soziale Wissenschaften",
    "section_classic_i": "I - Informatik & Kommunikation",
    "section_general_a3d": "A3D - Architektur, Design und nachhaltige Entwicklung",
    "section_general_acv": "ACV - Kunst und visuelle Kommunikation",
    "section_general_cc": "CC - Kommunikation und Organisation",
    "section_general_cf": "CF - Finanzen",
    "section_general_cg": "CG - Management",
    "section_general_cm": "CM - Verwaltung und Handel",
    "section_general_ed": "ED - Pädagogenausbildung",
    "section_general_gh": "GH - Hospitality Management",
    "section_general_ig": "IG - Ingenieurwesen",
    "section_general_in": "IN - Informatik",
    "section_general_mm": "MM - Marketing, Medien und Kommunikation",
    "section_general_ps": "PS - Gesundheits- und Sozialberufe",
    "section_general_se": "SE - Umweltwissenschaften",
    "section_general_sh": "SH - Gesundheitswissenschaften",
    "section_general_si": "SI - Ausbildung zur Krankenschwester",
    "section_general_sn": "SN - Naturwissenschaften",
    "section_general_so": "SO - Sozialwissenschaften",
    "select_term": "Periode auswählen",
    "semester": "Semester",
    "semesters": "Semester",
    "settings": "Einstellungen",
    "setup": "Einrichtung",
    "sort_by": "Sortieren",
    "storage_error": "Es ist ein Fehler beim Laden Ihrer gespeicherten Daten aufgetreten, daher wurden sie gelöscht.",
    "subject": "Fach",
    "system": "System",
    "system_language": "Systemsprache",
    "term": "Periode",
    "test": "Prüfung",
    "theme": "Design",
    "theme_dark": "Dunkel",
    "theme_light": "Hell",
    "theme_system": "System (empfohlen)",
    "to_100th": "Zum 100-tel",
    "to_10th": "Zum 10-tel",
    "to_integer": "Zur Ganzzahl",
    "trimester": "Trimester",
    "trimesters": "Trimester",
    "up": "Nach oben",
    "variant": "Variante",
    "variant_classic_l": "L - Lateinisch",
    "variant_classic_zh": "ZH - Chinesisch",
    "variant_general_a": "A - Fortsetzung des Deutschen",
    "variant_general_ad": "AD - Anpassungsklasse",
    "variant_general_adf": "ADF - Französische Anpassungsklasse",
    "variant_general_f": "F - Beginn des Deutschen",
    "variant_general_fr": "FR - Frankophones Regime",
    "variant_general_ia": "IA - Deutsch lernen",
    "variant_general_if": "IF - Französisch lernen",
    "variant_general_p": "P - Vorbereitungsweg",
    "variant_general_pf": "PF - French Preparation Way",
    "year": "Jahr",
    "year_overview": "Jahresübersicht",
    "yearly_average": "Jahresdurchschnitt",
    "yes": "Ja",
  };

  static const _lbValues = {
    "about": "Informatiounen",
    "about_text": "NightDream Games\nEntwéckler - Damien Pirotte\nVisuell Identitéit - Ellia Walrave\nTesting - Louis Colbus",
    "add": "Zoufügen",
    "add_group": "Grupp zoufügen",
    "add_subject": "Fach zoufügen",
    "add_subjects": "Fächer zoufügen",
    "add_test": "Prüfung zoufügen",
    "app_name": "Graded",
    "app_version": "App-Versioun",
    "appearance": "Ausgesinn",
    "average": "Moyenne",
    "az": "A-Z",
    "basic": "Basic",
    "bonus": "Bonus:",
    "cancel": "Ofbriechen",
    "change_class": "Klass änneren",
    "change_class_summary": "Klickt fir är aktuell Klass ze änneren. All gespäichert Notten ginn dobäi geläscht.",
    "class_string": "Klass",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffizienten",
    "coming_soon": "Deemnächst verfügbar",
    "confirm": "Bestätegung",
    "confirm_delete": "Sidd Dir sécher datt Dir all Är gespäichert Notten läschen wëllt?",
    "contact": "Kontakt",
    "custom": "Personaliséiert",
    "custom_rating_system": "Personaliséierten Bewäertungssystem",
    "default_string": "Default",
    "delete": "Läschen",
    "down": "No ënnen",
    "edit": "Beaarbechten",
    "edit_group": "Grupp beaarbechten",
    "edit_subject": "Fach beaarbechten",
    "edit_subjects": "Fächer beaarbechten",
    "edit_subjects_summary": "Klickt fir är Fächer ze beaarbechten",
    "edit_test": "Prüfung beaarbechten",
    "email": "contact@nightdreamgames.com",
    "english": "English",
    "enter_unique": "Gidd en eendeitegen Numm un",
    "exam": "Examen",
    "exams": "Examen",
    "export_details": "//TODO",
    "export_string": "Exportéieren",
    "french": "Français",
    "general": "General",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Graded",
    "grade": "Notte",
    "grades": "Notten",
    "group": "Grupp",
    "half_down": "Hallef no ënnen",
    "half_up": "Hallef no uewen",
    "import_details": "//TODO",
    "import_error": "Et ass e Feeler beim Importéieren vun ärem Backup opgetrueden.",
    "import_string": "Importéieren",
    "import_success": "Backup erfollegräich importéiert.",
    "invalid": "Ongëlteg",
    "language": "Sprooch",
    "licenses": "Lizenzen",
    "lux_system": "Lëtzebuergeschen Schoulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "more_options": "Méi Optiounen",
    "name": "Numm",
    "next": "Weider",
    "no": "Nee",
    "not_set": "Net definéiert",
    "note": "Umierkung:",
    "note_text": "Dir kënnt är Fächer an aner Optiounen spéider ëmmer nach an den Astellungen beaarbechten",
    "ok": "OK",
    "open": "Öffnen",
    "other_system": "Aneren Schoulsystem",
    "previous": "Zeréck",
    "rating_system": "Bewäertungssystem",
    "reset": "Notten zerécksetzen",
    "reset_summary": "All gespäichert Notten läschen an d'App zeréckzesetzen",
    "round_to": "Ronnen bis",
    "rounding_mode": "Ofronnungsmodus",
    "save": "Späicheren",
    "school_system": "Schoulsystem",
    "section": "Sektioun",
    "section_classic_a": "A - Sproochen",
    "section_classic_b": "B - Mathematik",
    "section_classic_c": "C - Naturwëssenschaften",
    "section_classic_d": "D - Wirtschaft",
    "section_classic_e": "E - Konscht",
    "section_classic_f": "F - Musek",
    "section_classic_g": "G - Mënschlech an sozial Wëssenschaften",
    "section_classic_i": "I - Informatik & Kommunikatioun",
    "section_general_a3d": "//TODO",
    "section_general_acv": "//TODO",
    "section_general_cc": "//TODO",
    "section_general_cf": "//TODO",
    "section_general_cg": "//TODO",
    "section_general_cm": "//TODO",
    "section_general_ed": "//TODO",
    "section_general_gh": "//TODO",
    "section_general_ig": "//TODO",
    "section_general_in": "//TODO",
    "section_general_mm": "//TODO",
    "section_general_ps": "//TODO",
    "section_general_se": "//TODO",
    "section_general_sh": "//TODO",
    "section_general_si": "//TODO",
    "section_general_sn": "//TODO",
    "section_general_so": "//TODO",
    "select_term": "Period auswielen",
    "semester": "Semester",
    "semesters": "Semester",
    "settings": "Astellungen",
    "setup": "Ariichtung",
    "sort_by": "Sortéieren",
    "storage_error": "Et ass e Feeler beim Lueden vun ären gespäicherten Donnéeën opgetrueden, dofir goufen se geläscht.",
    "subject": "Fach",
    "system": "System",
    "system_language": "Systemsprooch",
    "term": "Periode",
    "test": "Prüfung",
    "theme": "Design",
    "theme_dark": "Donkel",
    "theme_light": "Hell",
    "theme_system": "System (empfuelen)",
    "to_100th": "Zum 100-tel",
    "to_10th": "Zum 10-tel",
    "to_integer": "Zur Ganzzuel",
    "trimester": "Trimester",
    "trimesters": "Trimester",
    "up": "No uewen",
    "variant": "Variante",
    "variant_classic_l": "L - Latäin",
    "variant_classic_zh": "ZH - Chineesesch",
    "variant_general_a": "//TODO",
    "variant_general_ad": "//TODO",
    "variant_general_adf": "//TODO",
    "variant_general_f": "//TODO",
    "variant_general_fr": "//TODO",
    "variant_general_ia": "//TODO",
    "variant_general_if": "//TODO",
    "variant_general_p": "//TODO",
    "variant_general_pf": "//TODO",
    "year": "Joer",
    "year_overview": "Joresiwwersiicht",
    "yearly_average": "Joresmoyenne",
    "yes": "Jo",
  };

  static const _allValues = {
    "en": _enValues,
    "fr": _frValues,
    "de": _deValues,
    "lb": _lbValues,
  };

  Translations(Locale locale) {
    _locale = locale;
    _localizedValues = {};
  }

  static late Locale _locale;

  static String _getText(String key) => _localizedValues[key] ?? '** $key not found';

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static Future<Translations> load(Locale locale) async {
    final translations = Translations(locale);
    _localizedValues = _allValues[locale.toString()]!;
    return translations;
  }
}

class TranslationsDelegate extends LocalizationsDelegate<Translations> {
  const TranslationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('fr'),
    Locale('de'),
    Locale('lb'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<Translations> load(Locale locale) => Translations.load(locale);

  @override
  bool shouldReload(TranslationsDelegate old) => false;
}
