// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: public_member_api_docs, prefer_single_quotes, avoid_escaping_inner_quotes, prefer_const_constructors, sort_constructors_first, always_specify_types

import 'dart:async';

import 'package:flutter/widgets.dart';

/// A class generated by flappy_translator package containing localized strings
class I18n {
  String get a => _getText("a");

  String get about => _getText("about");

  String get about_text => _getText("about_text");

  String get add => _getText("add");

  String get add_subject => _getText("add_subject");

  String get add_subjects => _getText("add_subjects");

  String get add_test => _getText("add_test");

  String get app_name => _getText("app_name");

  String get app_version => _getText("app_version");

  String get appearance => _getText("appearance");

  String get average => _getText("average");

  String get az => _getText("az");

  String get b => _getText("b");

  String get basic => _getText("basic");

  String get bonus => _getText("bonus");

  String get c => _getText("c");

  String get change_class => _getText("change_class");

  String get change_class_summary => _getText("change_class_summary");

  String get chinese => _getText("chinese");

  String get class_string => _getText("class_string");

  String get classic => _getText("classic");

  String get coefficient => _getText("coefficient");

  String get coefficient_dots => _getText("coefficient_dots");

  String get coefficients => _getText("coefficients");

  String get confirm => _getText("confirm");

  String get confirm_delete => _getText("confirm_delete");

  String get contact => _getText("contact");

  String get custom => _getText("custom");

  String get custom_rating_system => _getText("custom_rating_system");

  String get d => _getText("d");

  String get dark_theme => _getText("dark_theme");

  String get default_string => _getText("default_string");

  String get delete => _getText("delete");

  String get down => _getText("down");

  String get e => _getText("e");

  String get edit => _getText("edit");

  String get edit_subject => _getText("edit_subject");

  String get edit_subjects => _getText("edit_subjects");

  String get edit_subjects_summary => _getText("edit_subjects_summary");

  String get edit_test => _getText("edit_test");

  String get email => _getText("email");

  String get english => _getText("english");

  String get enter_valid_number => _getText("enter_valid_number");

  String get f => _getText("f");

  String get french => _getText("french");

  String get g => _getText("g");

  String get general => _getText("general");

  String get german => _getText("german");

  String get github => _getText("github");

  String get github_summary => _getText("github_summary");

  String get grade => _getText("grade");

  String get grade_sample1 => _getText("grade_sample1");

  String get grade_sample2 => _getText("grade_sample2");

  String get grade_sample3 => _getText("grade_sample3");

  String get grades => _getText("grades");

  String get half_down => _getText("half_down");

  String get half_up => _getText("half_up");

  String get i => _getText("i");

  String get language => _getText("language");

  String get latin => _getText("latin");

  String get licenses => _getText("licenses");

  String get light_mode_auto => _getText("light_mode_auto");

  String get light_mode_off => _getText("light_mode_off");

  String get light_mode_on => _getText("light_mode_on");

  String get lux_system => _getText("lux_system");

  String get luxemburgish => _getText("luxemburgish");

  String get maximum => _getText("maximum");

  String get minus => _getText("minus");

  String get more_options => _getText("more_options");

  String get name => _getText("name");

  String get next => _getText("next");

  String get no => _getText("no");

  String get not_set => _getText("not_set");

  String get note => _getText("note");

  String get note_text => _getText("note_text");

  String get ok => _getText("ok");

  String get one => _getText("one");

  String get open => _getText("open");

  String get other_system => _getText("other_system");

  String get plus => _getText("plus");

  String get previous => _getText("previous");

  String get rating_system => _getText("rating_system");

  String get reset => _getText("reset");

  String get reset_summary => _getText("reset_summary");

  String get round_to => _getText("round_to");

  String get rounding_mode => _getText("rounding_mode");

  String get school_system => _getText("school_system");

  String get section => _getText("section");

  String get select_term => _getText("select_term");

  String get semester_1 => _getText("semester_1");

  String get semester_2 => _getText("semester_2");

  String get semesters => _getText("semesters");

  String get settings => _getText("settings");

  String get setup => _getText("setup");

  String get slash => _getText("slash");

  String get sort_by => _getText("sort_by");

  String get subject => _getText("subject");

  String get system => _getText("system");

  String get term => _getText("term");

  String get test => _getText("test");

  String get to_100th => _getText("to_100th");

  String get to_10th => _getText("to_10th");

  String get to_integer => _getText("to_integer");

  String get trimester_1 => _getText("trimester_1");

  String get trimester_2 => _getText("trimester_2");

  String get trimester_3 => _getText("trimester_3");

  String get trimesters => _getText("trimesters");

  String get up => _getText("up");

  String get variant => _getText("variant");

  String get year => _getText("year");

  String get yes => _getText("yes");

  String get zero => _getText("zero");

  static late Map<String, String> _localizedValues;

  static const _enValues = {
    "a": "A - Languages",
    "about": "About",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Add",
    "add_subject": "Add subject",
    "add_subjects": "Add subjects",
    "add_test": "Add test",
    "app_name": "Grade.ly",
    "app_version": "App version",
    "appearance": "Appearance",
    "average": "Average",
    "az": "A-Z",
    "b": "B - Mathematics",
    "basic": "Basic",
    "bonus": "Bonus:",
    "c": "C - Natural sciences",
    "change_class": "Change class",
    "change_class_summary":
        "Click to change your current class. This will delete all your saved grades.",
    "chinese": "Chinese",
    "class_string": "Class",
    "classic": "Classic",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "confirm": "Confirm",
    "confirm_delete": "Are you sure you want to delete all your saved grades?",
    "contact": "Contact us",
    "custom": "Custom",
    "custom_rating_system": "Custom rating system",
    "d": "D - Economics",
    "dark_theme": "Dark mode",
    "default_string": "Default",
    "delete": "Delete",
    "down": "Down",
    "e": "E - Art",
    "edit": "Edit",
    "edit_subject": "Edit subject",
    "edit_subjects": "Edit subjects",
    "edit_subjects_summary": "Click to edit your subjects",
    "edit_test": "Edit test",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Enter a valid number",
    "f": "F - Music",
    "french": "Français",
    "g": "G - Human and social sciences",
    "general": "General",
    "german": "Deutsch",
    "github": "GitHub repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Grade",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Grades",
    "half_down": "Half down",
    "half_up": "Half up",
    "i": "I - Informatics",
    "language": "Language",
    "latin": "Latin",
    "licenses": "Licenses",
    "light_mode_auto": "Auto (recommended)",
    "light_mode_off": "Off",
    "light_mode_on": "On",
    "lux_system": "Luxemburgish school system",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "More options",
    "name": "Name",
    "next": "Next",
    "no": "No",
    "not_set": "Not set",
    "note": "Note:",
    "note_text":
        "You can always edit your subjects and other options in the settings later",
    "ok": "Ok",
    "one": "1",
    "open": "Open",
    "other_system": "Other school system",
    "plus": "+",
    "previous": "Previous",
    "rating_system": "Rating system",
    "reset": "Reset Grades",
    "reset_summary": "Delete all saved grades and reset app",
    "round_to": "Round to",
    "rounding_mode": "Rounding mode",
    "school_system": "School system",
    "section": "Section",
    "select_term": "Select term",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semesters",
    "settings": "Settings",
    "setup": "Setup",
    "slash": "/",
    "sort_by": "Sort by",
    "subject": "Subject",
    "system": "System",
    "term": "Term",
    "test": "Test",
    "to_100th": "To 100-th",
    "to_10th": "To 10-th",
    "to_integer": "To integer",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimesters",
    "up": "Up",
    "variant": "Variant",
    "year": "Year",
    "yes": "Yes",
    "zero": "0",
  };

  static const _frValues = {
    "a": "A - Langues",
    "about": "À propos",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Ajouter",
    "add_subject": "Ajouter une matière",
    "add_subjects": "Ajouter des matières",
    "add_test": "Ajouter un devoir",
    "app_name": "Grade.ly",
    "app_version": "Version de l'application",
    "appearance": "Apparence",
    "average": "Moyenne",
    "az": "A-Z",
    "b": "B - Mathematiques",
    "basic": "Basique",
    "bonus": "Bonus:",
    "c": "C - Sciences naturelles",
    "change_class": "Changer la classe",
    "change_class_summary":
        "Cliquez pour changer votre classe actuelle. Cela supprimera toutes vos notes sauvegardées.",
    "chinese": "Chinois",
    "class_string": "Classe",
    "classic": "Classique",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "confirm": "Confirmation",
    "confirm_delete":
        "Êtes-vous sûr de vouloir supprimer toutes vos notes enregistrées ?",
    "contact": "Contact",
    "custom": "Personnalisé",
    "custom_rating_system": "Système de notation personnalisé",
    "d": "D - Economie",
    "dark_theme": "Mode sombre",
    "default_string": "Par défaut",
    "delete": "Supprimer",
    "down": "Vers le bas",
    "e": "E - Artistique",
    "edit": "Modifier",
    "edit_subject": "Modifier une matière",
    "edit_subjects": "Modifier matières",
    "edit_subjects_summary": "Cliquez pour modifier vos matières.",
    "edit_test": "Modifier un devoir",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Entrez un nombre valide",
    "f": "F - Musique",
    "french": "Français",
    "g": "G - Sciences humaines et sociales",
    "general": "Général",
    "german": "Deutsch",
    "github": "Repository GitHub",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Note",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Notes",
    "half_down": "A moitié vers le bas",
    "half_up": "A moitié vers le haut",
    "i": "I - Informatique & Communication",
    "language": "Langue",
    "latin": "Latin",
    "licenses": "Licenses",
    "light_mode_auto": "Auto (recommandé)",
    "light_mode_off": "Off",
    "light_mode_on": "On",
    "lux_system": "Système scolaire luxembourgeois",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Plus d'options",
    "name": "Nom",
    "next": "Suivant",
    "no": "Non",
    "not_set": "Non défini",
    "note": "Note:",
    "note_text":
        "Vous pouvez toujours modifier vos matières et les autres options dans les paramètres plus tard",
    "ok": "Ok",
    "one": "1",
    "open": "Ouvrir",
    "other_system": "Autre système scolaire",
    "plus": "+",
    "previous": "Précédent",
    "rating_system": "Système de notation",
    "reset": "Réinitialiser les notes",
    "reset_summary":
        "Supprimer toutes les notes enregistrées et réinitialiser l'application",
    "round_to": "Arrondir à",
    "rounding_mode": "Mode arrondissage",
    "school_system": "Système scolaire",
    "section": "Section",
    "select_term": "Sélectionner période",
    "semester_1": "Semestre 1",
    "semester_2": "Semestre 2",
    "semesters": "Semestres",
    "settings": "Options",
    "setup": "Configuration",
    "slash": "/",
    "sort_by": "Trier par",
    "subject": "Matière",
    "system": "Système",
    "term": "Période",
    "test": "Devoir",
    "to_100th": "Au 100ème",
    "to_10th": "Au 10ème",
    "to_integer": "A l'entier",
    "trimester_1": "Trimestre 1",
    "trimester_2": "Trimestre 2",
    "trimester_3": "Trimestre 3",
    "trimesters": "Trimestres",
    "up": "Vers le haut",
    "variant": "Variante",
    "year": "Année",
    "yes": "Oui",
    "zero": "0",
  };

  static const _deValues = {
    "a": "A - Sprachen",
    "about": "Informationen",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Hinzufügen",
    "add_subject": "Fach hinzufügen",
    "add_subjects": "Fächer hinzufügen",
    "add_test": "Prüfung hinzufügen",
    "app_name": "Grade.ly",
    "app_version": "App-Version",
    "appearance": "Aussehen",
    "average": "Durchschnitt",
    "az": "A-Z",
    "b": "B - Mathematik",
    "basic": "Basic",
    "bonus": "Bonus:",
    "c": "C - Naturwissenschaften",
    "change_class": "Klasse ändern",
    "change_class_summary":
        "Klicken Sie um Ihre aktuelle Klasse zu ändern. Alle gespeicherten Noten werden dabei gelöscht.",
    "chinese": "Chinesisch",
    "class_string": "Klasse",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffiziente",
    "confirm": "Bestätigung",
    "confirm_delete":
        "Sind Sie sicher, dass Sie alle Ihre gespeicherten Noten löschen wollen?",
    "contact": "Kontakt",
    "custom": "Personalisiert",
    "custom_rating_system": "Personalisiertes Bewertungssystem",
    "d": "D - Wirtschaft",
    "dark_theme": "Dunkel-Modus",
    "default_string": "Default",
    "delete": "Löschen",
    "down": "Nach unten",
    "e": "E - Kunst",
    "edit": "Bearbeiten",
    "edit_subject": "Fach bearbeiten",
    "edit_subjects": "Fächer bearbeiten",
    "edit_subjects_summary": "Klicken Sie um Ihre Fächer zu bearbeiten",
    "edit_test": "Prüfing bearbeiten",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Geben Sie eine gültige Nummer ein",
    "f": "F - Musik",
    "french": "Français",
    "g": "G -Menschliche und soziale Wissenschaften",
    "general": "Allgemein",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Note",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Noten",
    "half_down": "Halb nach unten",
    "half_up": "Halb nach oben",
    "i": "I - Informatik & Kommunikation",
    "language": "Sprache",
    "latin": "Lateinisch",
    "licenses": "Lizenzen",
    "light_mode_auto": "Auto (empfohlen)",
    "light_mode_off": "Aus",
    "light_mode_on": "An",
    "lux_system": "Luxemburgisches Schulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Mehr Optionen",
    "name": "Name",
    "next": "Weiter",
    "no": "Nein",
    "not_set": "Nicht definiert",
    "note": "Anmerkung:",
    "note_text":
        "Sie können Ihre Fächer und andere Optionen später immer noch in den Einstellungen bearbeiten",
    "ok": "Ok",
    "one": "1",
    "open": "Öffnen",
    "other_system": "Anderes Schulsystem",
    "plus": "+",
    "previous": "Zurück",
    "rating_system": "Bewertungssystem",
    "reset": "Noten zurücksetzen",
    "reset_summary": "Alle gespeicherten Noten löschen und App zurücksetzen",
    "round_to": "Runden bis",
    "rounding_mode": "Abrundungsmodus",
    "school_system": "Schulsystem",
    "section": "Section",
    "select_term": "Periode auswählen",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semester",
    "settings": "Einstellungen",
    "setup": "Einrichtung",
    "slash": "/",
    "sort_by": "Sortieren",
    "subject": "Fach",
    "system": "System",
    "term": "Periode",
    "test": "Prüfung",
    "to_100th": "Zum 100-ten",
    "to_10th": "Zum 10-ten",
    "to_integer": "Zu Ganzzahl",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimester",
    "up": "Nach oben",
    "variant": "Variante",
    "year": "Jahr",
    "yes": "Ja",
    "zero": "0",
  };

  static const _luValues = {
    "a": "A - Sproochen",
    "about": "Informatiounen",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Zoufügen",
    "add_subject": "Fach zoufügen",
    "add_subjects": "Fächer zoufügen",
    "add_test": "Prüfung zoufügen",
    "app_name": "Grade.ly",
    "app_version": "App-Versioun",
    "appearance": "Ausgesinn",
    "average": "Moyenne",
    "az": "A-Z",
    "b": "B - Mathematik",
    "basic": "Basic",
    "bonus": "Bonus:",
    "c": "C - Naturwëssenschaften",
    "change_class": "Klass änneren",
    "change_class_summary":
        "Klickt fir är aktuell Klass ze änneren. All gespäichert Notten ginn dobäi geläscht.",
    "chinese": "Chineesesch",
    "class_string": "Klass",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffizienten",
    "confirm": "Bestätegung",
    "confirm_delete":
        "Sidd Dir sécher datt Dir all Är gespäichert Notten läschen wëllt?",
    "contact": "Kontakt",
    "custom": "Personaliséiert",
    "custom_rating_system": "Personaliséierten Bewäertungssystem",
    "d": "D - Wirtschaft",
    "dark_theme": "Donkel-Modus",
    "default_string": "Default",
    "delete": "Läschen",
    "down": "No ënnen",
    "e": "E - Konscht",
    "edit": "Beaarbechten",
    "edit_subject": "Fach beaarbechten",
    "edit_subjects": "Fächer beaarbechten",
    "edit_subjects_summary": "Klickt fir är Fächer ze beaarbechten",
    "edit_test": "Prüfung beaarbechten",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Gidd eng gëlteg Nummer an",
    "f": "F - Musek",
    "french": "Français",
    "g": "G - Mënschlech an sozial Wëssenschaften",
    "general": "Allgemeng",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Notte",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Notten",
    "half_down": "Hallef no ënnen",
    "half_up": "Hallef no uewen",
    "i": "I - Informatik & Kommunikatioun",
    "language": "Sprooch",
    "latin": "Latäin",
    "licenses": "Lizenzen",
    "light_mode_auto": "Auto (empfuelen)",
    "light_mode_off": "Aus",
    "light_mode_on": "Un",
    "lux_system": "Lëtzebuergeschen Schoulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Méi Optiounen",
    "name": "Numm",
    "next": "Weider",
    "no": "Nee",
    "not_set": "Net definéiert",
    "note": "Umierkung:",
    "note_text":
        "Dir kënnt är Fächer an aner Optiounen spéider ëmmer nach an den Astellungen beaarbechten",
    "ok": "Ok",
    "one": "1",
    "open": "Öffnen",
    "other_system": "Aneren Schoulsystem",
    "plus": "+",
    "previous": "Zeréck",
    "rating_system": "Bewäertungssystem",
    "reset": "Notten zerécksetzen",
    "reset_summary": "All gespäichert Notten läschen an d'App zeréckzesetzen",
    "round_to": "Ronnen bis",
    "rounding_mode": "Ofronnungsmodus",
    "school_system": "Schoulsystem",
    "section": "Sektioun",
    "select_term": "Period auswielen",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semester",
    "settings": "Astellungen",
    "setup": "Ariichtung",
    "slash": "/",
    "sort_by": "Sortéieren",
    "subject": "Fach",
    "system": "System",
    "term": "Periode",
    "test": "Prüfung",
    "to_100th": "Zum 100-tel",
    "to_10th": "Zum 10-tel",
    "to_integer": "Zur Ganzzuel",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimester",
    "up": "No uewen",
    "variant": "Variante",
    "year": "Joer",
    "yes": "Jo",
    "zero": "0",
  };

  static const _allValues = {
    "en": _enValues,
    "fr": _frValues,
    "de": _deValues,
    "lu": _luValues,
  };

  I18n(Locale locale) : _locale = locale {
    _localizedValues = {};
  }

  final Locale _locale;

  static I18n of(BuildContext context) =>
      Localizations.of<I18n>(context, I18n)!;

  String _getText(String key) => _localizedValues[key] ?? '** $key not found';

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()]!;
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('fr'),
    Locale('de'),
    Locale('lu'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}
