// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: public_member_api_docs, prefer_single_quotes, avoid_escaping_inner_quotes, prefer_const_constructors, sort_constructors_first, always_specify_types

import 'dart:async';

import 'package:flutter/widgets.dart';

/// A class generated by flappy_translator package containing localized strings
class Translations {
  static String get section_classic_a => _getText("section_classic_a");

  static String get about => _getText("about");

  static String get about_text => _getText("about_text");

  static String get add => _getText("add");

  static String get add_subject => _getText("add_subject");

  static String get add_subjects => _getText("add_subjects");

  static String get add_test => _getText("add_test");

  static String get app_name => _getText("app_name");

  static String get app_version => _getText("app_version");

  static String get appearance => _getText("appearance");

  static String get average => _getText("average");

  static String get az => _getText("az");

  static String get section_classic_b => _getText("section_classic_b");

  static String get basic => _getText("basic");

  static String get bonus => _getText("bonus");

  static String get section_classic_c => _getText("section_classic_c");

  static String get change_class => _getText("change_class");

  static String get change_class_summary => _getText("change_class_summary");

  static String get chinese => _getText("chinese");

  static String get class_string => _getText("class_string");

  static String get classic => _getText("classic");

  static String get coefficient => _getText("coefficient");

  static String get coefficient_dots => _getText("coefficient_dots");

  static String get coefficients => _getText("coefficients");

  static String get confirm => _getText("confirm");

  static String get confirm_delete => _getText("confirm_delete");

  static String get contact => _getText("contact");

  static String get custom => _getText("custom");

  static String get custom_rating_system => _getText("custom_rating_system");

  static String get section_classic_d => _getText("section_classic_d");

  static String get default_string => _getText("default_string");

  static String get delete => _getText("delete");

  static String get down => _getText("down");

  static String get section_classic_e => _getText("section_classic_e");

  static String get edit => _getText("edit");

  static String get edit_subject => _getText("edit_subject");

  static String get edit_subjects => _getText("edit_subjects");

  static String get edit_subjects_summary => _getText("edit_subjects_summary");

  static String get edit_test => _getText("edit_test");

  static String get email => _getText("email");

  static String get english => _getText("english");

  static String get enter_valid_number => _getText("enter_valid_number");

  static String get section_classic_f => _getText("section_classic_f");

  static String get french => _getText("french");

  static String get section_classic_g => _getText("section_classic_g");

  static String get general => _getText("general");

  static String get german => _getText("german");

  static String get github => _getText("github");

  static String get github_summary => _getText("github_summary");

  static String get grade => _getText("grade");

  static String get grade_sample1 => _getText("grade_sample1");

  static String get grade_sample2 => _getText("grade_sample2");

  static String get grade_sample3 => _getText("grade_sample3");

  static String get grades => _getText("grades");

  static String get half_down => _getText("half_down");

  static String get half_up => _getText("half_up");

  static String get section_classic_i => _getText("section_classic_i");

  static String get language => _getText("language");

  static String get latin => _getText("latin");

  static String get licenses => _getText("licenses");

  static String get lux_system => _getText("lux_system");

  static String get luxemburgish => _getText("luxemburgish");

  static String get maximum => _getText("maximum");

  static String get minus => _getText("minus");

  static String get more_options => _getText("more_options");

  static String get name => _getText("name");

  static String get next => _getText("next");

  static String get no => _getText("no");

  static String get not_set => _getText("not_set");

  static String get note => _getText("note");

  static String get note_text => _getText("note_text");

  static String get ok => _getText("ok");

  static String get one => _getText("one");

  static String get open => _getText("open");

  static String get other_system => _getText("other_system");

  static String get plus => _getText("plus");

  static String get previous => _getText("previous");

  static String get rating_system => _getText("rating_system");

  static String get reset => _getText("reset");

  static String get reset_summary => _getText("reset_summary");

  static String get round_to => _getText("round_to");

  static String get rounding_mode => _getText("rounding_mode");

  static String get school_system => _getText("school_system");

  static String get section => _getText("section");

  static String get select_term => _getText("select_term");

  static String get semester_1 => _getText("semester_1");

  static String get semester_2 => _getText("semester_2");

  static String get semesters => _getText("semesters");

  static String get settings => _getText("settings");

  static String get setup => _getText("setup");

  static String get slash => _getText("slash");

  static String get sort_by => _getText("sort_by");

  static String get subject => _getText("subject");

  static String get system => _getText("system");

  static String get term => _getText("term");

  static String get test => _getText("test");

  static String get theme => _getText("theme");

  static String get theme_dark => _getText("theme_dark");

  static String get theme_light => _getText("theme_light");

  static String get theme_system => _getText("theme_system");

  static String get to_100th => _getText("to_100th");

  static String get to_10th => _getText("to_10th");

  static String get to_integer => _getText("to_integer");

  static String get trimester_1 => _getText("trimester_1");

  static String get trimester_2 => _getText("trimester_2");

  static String get trimester_3 => _getText("trimester_3");

  static String get trimesters => _getText("trimesters");

  static String get up => _getText("up");

  static String get variant => _getText("variant");

  static String get year => _getText("year");

  static String get yes => _getText("yes");

  static String get zero => _getText("zero");

  static late Map<String, String> _localizedValues;

  static const _enValues = {
    "section_classic_a": "A - Languages",
    "about": "About",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Add",
    "add_subject": "Add subject",
    "add_subjects": "Add subjects",
    "add_test": "Add test",
    "app_name": "Grade.ly",
    "app_version": "App version",
    "appearance": "Appearance",
    "average": "Average",
    "az": "A-Z",
    "section_classic_b": "B - Mathematics",
    "basic": "Basic",
    "bonus": "Bonus:",
    "section_classic_c": "C - Natural sciences",
    "change_class": "Change class",
    "change_class_summary":
        "Click to change your current class. This will delete all your saved grades.",
    "chinese": "Chinese",
    "class_string": "Class",
    "classic": "Classic",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "confirm": "Confirm",
    "confirm_delete": "Are you sure you want to delete all your saved grades?",
    "contact": "Contact us",
    "custom": "Custom",
    "custom_rating_system": "Custom rating system",
    "section_classic_d": "D - Economics",
    "default_string": "Default",
    "delete": "Delete",
    "down": "Down",
    "section_classic_e": "E - Art",
    "edit": "Edit",
    "edit_subject": "Edit subject",
    "edit_subjects": "Edit subjects",
    "edit_subjects_summary": "Click to edit your subjects",
    "edit_test": "Edit test",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Enter a valid number",
    "section_classic_f": "F - Music",
    "french": "Français",
    "section_classic_g": "G - Human and social sciences",
    "general": "General",
    "german": "Deutsch",
    "github": "GitHub repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Grade",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Grades",
    "half_down": "Half down",
    "half_up": "Half up",
    "section_classic_i": "I - Informatics",
    "language": "Language",
    "latin": "Latin",
    "licenses": "Licenses",
    "lux_system": "Luxemburgish school system",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "More options",
    "name": "Name",
    "next": "Next",
    "no": "No",
    "not_set": "Not set",
    "note": "Note:",
    "note_text":
        "You can always edit your subjects and other options in the settings later",
    "ok": "Ok",
    "one": "1",
    "open": "Open",
    "other_system": "Other school system",
    "plus": "+",
    "previous": "Previous",
    "rating_system": "Rating system",
    "reset": "Reset Grades",
    "reset_summary": "Delete all saved grades and reset app",
    "round_to": "Round to",
    "rounding_mode": "Rounding mode",
    "school_system": "School system",
    "section": "Section",
    "select_term": "Select term",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semesters",
    "settings": "Settings",
    "setup": "Setup",
    "slash": "/",
    "sort_by": "Sort by",
    "subject": "Subject",
    "system": "System",
    "term": "Term",
    "test": "Test",
    "theme": "Theme",
    "theme_dark": "Dark",
    "theme_light": "Light",
    "theme_system": "System (recommended)",
    "to_100th": "To 100-th",
    "to_10th": "To 10-th",
    "to_integer": "To integer",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimesters",
    "up": "Up",
    "variant": "Variant",
    "year": "Year",
    "yes": "Yes",
    "zero": "0",
  };

  static const _frValues = {
    "section_classic_a": "A - Langues",
    "about": "À propos",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Ajouter",
    "add_subject": "Ajouter une matière",
    "add_subjects": "Ajouter des matières",
    "add_test": "Ajouter un devoir",
    "app_name": "Grade.ly",
    "app_version": "Version de l'application",
    "appearance": "Apparence",
    "average": "Moyenne",
    "az": "A-Z",
    "section_classic_b": "B - Mathematiques",
    "basic": "Basique",
    "bonus": "Bonus:",
    "section_classic_c": "C - Sciences naturelles",
    "change_class": "Changer la classe",
    "change_class_summary":
        "Cliquez pour changer votre classe actuelle. Cela supprimera toutes vos notes sauvegardées.",
    "chinese": "Chinois",
    "class_string": "Classe",
    "classic": "Classique",
    "coefficient": "Coefficient",
    "coefficient_dots": "Coefficient:",
    "coefficients": "Coefficients",
    "confirm": "Confirmation",
    "confirm_delete":
        "Êtes-vous sûr de vouloir supprimer toutes vos notes enregistrées ?",
    "contact": "Contact",
    "custom": "Personnalisé",
    "custom_rating_system": "Système de notation personnalisé",
    "section_classic_d": "D - Economie",
    "default_string": "Par défaut",
    "delete": "Supprimer",
    "down": "Vers le bas",
    "section_classic_e": "E - Artistique",
    "edit": "Modifier",
    "edit_subject": "Modifier une matière",
    "edit_subjects": "Modifier matières",
    "edit_subjects_summary": "Cliquez pour modifier vos matières.",
    "edit_test": "Modifier un devoir",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Entrez un nombre valide",
    "section_classic_f": "F - Musique",
    "french": "Français",
    "section_classic_g": "G - Sciences humaines et sociales",
    "general": "Général",
    "german": "Deutsch",
    "github": "Repository GitHub",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Note",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Notes",
    "half_down": "A moitié vers le bas",
    "half_up": "A moitié vers le haut",
    "section_classic_i": "I - Informatique & Communication",
    "language": "Langue",
    "latin": "Latin",
    "licenses": "Licenses",
    "lux_system": "Système scolaire luxembourgeois",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Plus d'options",
    "name": "Nom",
    "next": "Suivant",
    "no": "Non",
    "not_set": "Non défini",
    "note": "Note:",
    "note_text":
        "Vous pouvez toujours modifier vos matières et les autres options dans les paramètres plus tard",
    "ok": "Ok",
    "one": "1",
    "open": "Ouvrir",
    "other_system": "Autre système scolaire",
    "plus": "+",
    "previous": "Précédent",
    "rating_system": "Système de notation",
    "reset": "Réinitialiser les notes",
    "reset_summary":
        "Supprimer toutes les notes enregistrées et réinitialiser l'application",
    "round_to": "Arrondir à",
    "rounding_mode": "Mode arrondissage",
    "school_system": "Système scolaire",
    "section": "Section",
    "select_term": "Sélectionner période",
    "semester_1": "Semestre 1",
    "semester_2": "Semestre 2",
    "semesters": "Semestres",
    "settings": "Options",
    "setup": "Configuration",
    "slash": "/",
    "sort_by": "Trier par",
    "subject": "Matière",
    "system": "Système",
    "term": "Période",
    "test": "Devoir",
    "theme": "Thème",
    "theme_dark": "Sombre",
    "theme_light": "Clair",
    "theme_system": "Système (recommandé)",
    "to_100th": "Au 100ème",
    "to_10th": "Au 10ème",
    "to_integer": "A l'entier",
    "trimester_1": "Trimestre 1",
    "trimester_2": "Trimestre 2",
    "trimester_3": "Trimestre 3",
    "trimesters": "Trimestres",
    "up": "Vers le haut",
    "variant": "Variante",
    "year": "Année",
    "yes": "Oui",
    "zero": "0",
  };

  static const _deValues = {
    "section_classic_a": "A - Sprachen",
    "about": "Informationen",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Hinzufügen",
    "add_subject": "Fach hinzufügen",
    "add_subjects": "Fächer hinzufügen",
    "add_test": "Prüfung hinzufügen",
    "app_name": "Grade.ly",
    "app_version": "App-Version",
    "appearance": "Aussehen",
    "average": "Durchschnitt",
    "az": "A-Z",
    "section_classic_b": "B - Mathematik",
    "basic": "Basic",
    "bonus": "Bonus:",
    "section_classic_c": "C - Naturwissenschaften",
    "change_class": "Klasse ändern",
    "change_class_summary":
        "Klicken Sie um Ihre aktuelle Klasse zu ändern. Alle gespeicherten Noten werden dabei gelöscht.",
    "chinese": "Chinesisch",
    "class_string": "Klasse",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffiziente",
    "confirm": "Bestätigung",
    "confirm_delete":
        "Sind Sie sicher, dass Sie alle Ihre gespeicherten Noten löschen wollen?",
    "contact": "Kontakt",
    "custom": "Personalisiert",
    "custom_rating_system": "Personalisiertes Bewertungssystem",
    "section_classic_d": "D - Wirtschaft",
    "default_string": "Default",
    "delete": "Löschen",
    "down": "Nach unten",
    "section_classic_e": "E - Kunst",
    "edit": "Bearbeiten",
    "edit_subject": "Fach bearbeiten",
    "edit_subjects": "Fächer bearbeiten",
    "edit_subjects_summary": "Klicken Sie um Ihre Fächer zu bearbeiten",
    "edit_test": "Prüfing bearbeiten",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Geben Sie eine gültige Nummer ein",
    "section_classic_f": "F - Musik",
    "french": "Français",
    "section_classic_g": "G -Menschliche und soziale Wissenschaften",
    "general": "Allgemein",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Note",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Noten",
    "half_down": "Halb nach unten",
    "half_up": "Halb nach oben",
    "section_classic_i": "I - Informatik & Kommunikation",
    "language": "Sprache",
    "latin": "Lateinisch",
    "licenses": "Lizenzen",
    "lux_system": "Luxemburgisches Schulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Mehr Optionen",
    "name": "Name",
    "next": "Weiter",
    "no": "Nein",
    "not_set": "Nicht definiert",
    "note": "Anmerkung:",
    "note_text":
        "Sie können Ihre Fächer und andere Optionen später immer noch in den Einstellungen bearbeiten",
    "ok": "Ok",
    "one": "1",
    "open": "Öffnen",
    "other_system": "Anderes Schulsystem",
    "plus": "+",
    "previous": "Zurück",
    "rating_system": "Bewertungssystem",
    "reset": "Noten zurücksetzen",
    "reset_summary": "Alle gespeicherten Noten löschen und App zurücksetzen",
    "round_to": "Runden bis",
    "rounding_mode": "Abrundungsmodus",
    "school_system": "Schulsystem",
    "section": "Section",
    "select_term": "Periode auswählen",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semester",
    "settings": "Einstellungen",
    "setup": "Einrichtung",
    "slash": "/",
    "sort_by": "Sortieren",
    "subject": "Fach",
    "system": "System",
    "term": "Periode",
    "test": "Prüfung",
    "theme": "Design",
    "theme_dark": "Dunkel",
    "theme_light": "Hell",
    "theme_system": "System (empfohlen)",
    "to_100th": "Zum 100-tel",
    "to_10th": "Zum 10-tel",
    "to_integer": "Zur Ganzzahl",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimester",
    "up": "Nach oben",
    "variant": "Variante",
    "year": "Jahr",
    "yes": "Ja",
    "zero": "0",
  };

  static const _luValues = {
    "section_classic_a": "A - Sproochen",
    "about": "Informatiounen",
    "about_text":
        "NightDream Games - FauconSpartiate\nVisual identity - Ellia Walrave\nTesting - AigleSpartiate",
    "add": "Zoufügen",
    "add_subject": "Fach zoufügen",
    "add_subjects": "Fächer zoufügen",
    "add_test": "Prüfung zoufügen",
    "app_name": "Grade.ly",
    "app_version": "App-Versioun",
    "appearance": "Ausgesinn",
    "average": "Moyenne",
    "az": "A-Z",
    "section_classic_b": "B - Mathematik",
    "basic": "Basic",
    "bonus": "Bonus:",
    "section_classic_c": "C - Naturwëssenschaften",
    "change_class": "Klass änneren",
    "change_class_summary":
        "Klickt fir är aktuell Klass ze änneren. All gespäichert Notten ginn dobäi geläscht.",
    "chinese": "Chineesesch",
    "class_string": "Klass",
    "classic": "Klassik",
    "coefficient": "Koeffizient",
    "coefficient_dots": "Koeffizient:",
    "coefficients": "Koeffizienten",
    "confirm": "Bestätegung",
    "confirm_delete":
        "Sidd Dir sécher datt Dir all Är gespäichert Notten läschen wëllt?",
    "contact": "Kontakt",
    "custom": "Personaliséiert",
    "custom_rating_system": "Personaliséierten Bewäertungssystem",
    "section_classic_d": "D - Wirtschaft",
    "default_string": "Default",
    "delete": "Läschen",
    "down": "No ënnen",
    "section_classic_e": "E - Konscht",
    "edit": "Beaarbechten",
    "edit_subject": "Fach beaarbechten",
    "edit_subjects": "Fächer beaarbechten",
    "edit_subjects_summary": "Klickt fir är Fächer ze beaarbechten",
    "edit_test": "Prüfung beaarbechten",
    "email": "contact.nightdreamgames@gmail.com",
    "english": "English",
    "enter_valid_number": "Gidd eng gëlteg Nummer an",
    "section_classic_f": "F - Musek",
    "french": "Français",
    "section_classic_g": "G - Mënschlech an sozial Wëssenschaften",
    "general": "Allgemeng",
    "german": "Deutsch",
    "github": "GitHub Repository",
    "github_summary": "https://github.com/NightDreamGames/Grade.ly",
    "grade": "Notte",
    "grade_sample1": "01",
    "grade_sample2": "01/60",
    "grade_sample3": "60",
    "grades": "Notten",
    "half_down": "Hallef no ënnen",
    "half_up": "Hallef no uewen",
    "section_classic_i": "I - Informatik & Kommunikatioun",
    "language": "Sprooch",
    "latin": "Latäin",
    "licenses": "Lizenzen",
    "lux_system": "Lëtzebuergeschen Schoulsystem",
    "luxemburgish": "Lëtzebuergesch",
    "maximum": "Maximum",
    "minus": "-",
    "more_options": "Méi Optiounen",
    "name": "Numm",
    "next": "Weider",
    "no": "Nee",
    "not_set": "Net definéiert",
    "note": "Umierkung:",
    "note_text":
        "Dir kënnt är Fächer an aner Optiounen spéider ëmmer nach an den Astellungen beaarbechten",
    "ok": "Ok",
    "one": "1",
    "open": "Öffnen",
    "other_system": "Aneren Schoulsystem",
    "plus": "+",
    "previous": "Zeréck",
    "rating_system": "Bewäertungssystem",
    "reset": "Notten zerécksetzen",
    "reset_summary": "All gespäichert Notten läschen an d'App zeréckzesetzen",
    "round_to": "Ronnen bis",
    "rounding_mode": "Ofronnungsmodus",
    "school_system": "Schoulsystem",
    "section": "Sektioun",
    "select_term": "Period auswielen",
    "semester_1": "Semester 1",
    "semester_2": "Semester 2",
    "semesters": "Semester",
    "settings": "Astellungen",
    "setup": "Ariichtung",
    "slash": "/",
    "sort_by": "Sortéieren",
    "subject": "Fach",
    "system": "System",
    "term": "Periode",
    "test": "Prüfung",
    "theme": "Design",
    "theme_dark": "Donkel",
    "theme_light": "Hell",
    "theme_system": "System (empfuelen)",
    "to_100th": "Zum 100-tel",
    "to_10th": "Zum 10-tel",
    "to_integer": "Zur Ganzzuel",
    "trimester_1": "Trimester 1",
    "trimester_2": "Trimester 2",
    "trimester_3": "Trimester 3",
    "trimesters": "Trimester",
    "up": "No uewen",
    "variant": "Variante",
    "year": "Joer",
    "yes": "Jo",
    "zero": "0",
  };

  static const _allValues = {
    "en": _enValues,
    "fr": _frValues,
    "de": _deValues,
    "lu": _luValues,
  };

  Translations(Locale locale) {
    _locale = locale;
    _localizedValues = {};
  }

  static late Locale _locale;

  static String _getText(String key) =>
      _localizedValues[key] ?? '** $key not found';

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static Future<Translations> load(Locale locale) async {
    final translations = Translations(locale);
    _localizedValues = _allValues[locale.toString()]!;
    return translations;
  }
}

class TranslationsDelegate extends LocalizationsDelegate<Translations> {
  const TranslationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('fr'),
    Locale('de'),
    Locale('lu'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<Translations> load(Locale locale) => Translations.load(locale);

  @override
  bool shouldReload(TranslationsDelegate old) => false;
}
